/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WashRouteImport } from './routes/wash'
import { Route as TerminiRouteImport } from './routes/termini'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PonteAdminRouteImport } from './routes/ponte-admin'
import { Route as DeployGuideRouteImport } from './routes/deploy-guide'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as BridgeAdminRouteImport } from './routes/bridge-admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PonteAdminIndexRouteImport } from './routes/ponte-admin.index'
import { Route as ShopSpedizioniRouteImport } from './routes/shop.spedizioni'
import { Route as ShopSaleRouteImport } from './routes/shop.sale'
import { Route as ShopResiRouteImport } from './routes/shop.resi'
import { Route as ShopFaqRouteImport } from './routes/shop.faq'
import { Route as ShopContattiRouteImport } from './routes/shop.contatti'
import { Route as ShopChiSiamoRouteImport } from './routes/shop.chi-siamo'
import { Route as ShopCarrelloRouteImport } from './routes/shop.carrello'
import { Route as ShopAccountRouteImport } from './routes/shop.account'
import { Route as PonteAdminWashDebugRouteImport } from './routes/ponte-admin.wash-debug'
import { Route as PonteAdminSyncRouteImport } from './routes/ponte-admin.sync'
import { Route as PonteAdminStoresRouteImport } from './routes/ponte-admin.stores'
import { Route as PonteAdminSiteSettingsRouteImport } from './routes/ponte-admin.site-settings'
import { Route as PonteAdminSiteSettingRouteImport } from './routes/ponte-admin.site-setting'
import { Route as PonteAdminShippingRouteImport } from './routes/ponte-admin.shipping'
import { Route as PonteAdminRevenueRouteImport } from './routes/ponte-admin.revenue'
import { Route as PonteAdminReferrerCheckRouteImport } from './routes/ponte-admin.referrer-check'
import { Route as PonteAdminProdottiRouteImport } from './routes/ponte-admin.prodotti'
import { Route as PonteAdminNewRouteImport } from './routes/ponte-admin.new'
import { Route as PonteAdminMigrateSupabaseRouteImport } from './routes/ponte-admin.migrate-supabase'
import { Route as PonteAdminLovableSyncRouteImport } from './routes/ponte-admin.lovable-sync'
import { Route as PonteAdminLogsRouteImport } from './routes/ponte-admin.logs'
import { Route as PonteAdminLoginRouteImport } from './routes/ponte-admin.login'
import { Route as PonteAdminExternalDbRouteImport } from './routes/ponte-admin.external-db'
import { Route as PonteAdminClonesHealthRouteImport } from './routes/ponte-admin.clones-health'
import { Route as PonteAdminCapiRouteImport } from './routes/ponte-admin.capi'
import { Route as PonteAdminApplePayRouteImport } from './routes/ponte-admin.apple-pay'
import { Route as PonteAdminIdRouteImport } from './routes/ponte-admin.$id'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as BridgeAdminStoresRouteImport } from './routes/bridge-admin.stores'
import { Route as BridgeAdminProdottiRouteImport } from './routes/bridge-admin.prodotti'
import { Route as BridgeAdminLoginRouteImport } from './routes/bridge-admin.login'
import { Route as ApiGenerateCheckoutRouteImport } from './routes/api/generate-checkout'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as DotwellKnownAppleDeveloperMerchantidDomainAssociationRouteImport } from './routes/[.]well-known.apple-developer-merchantid-domain-association'
import { Route as ShopProdottoSlugRouteImport } from './routes/shop.prodotto.$slug'
import { Route as ShopCheckoutWhopRouteImport } from './routes/shop.checkout.whop'
import { Route as ShopCheckoutDemoRouteImport } from './routes/shop.checkout.demo'
import { Route as ShopCategoriaSlugRouteImport } from './routes/shop.categoria.$slug'
import { Route as ApiPublicWhopWebhookRouteImport } from './routes/api.public.whop-webhook'
import { Route as ApiPublicSyncProductRouteImport } from './routes/api.public.sync-product'
import { Route as ApiPublicShopifyWebhookRouteImport } from './routes/api.public.shopify-webhook'
import { Route as ApiPublicRuntimeSupabaseEnvRouteImport } from './routes/api.public.runtime-supabase-env'
import { Route as ApiBridgePushShadowProductRouteImport } from './routes/api/bridge/push-shadow-product'
import { Route as ApiBridgeHandshakeRouteImport } from './routes/api/bridge/handshake'
import { Route as ApiPublicLovableSyncPushProductRouteImport } from './routes/api.public.lovable-sync.push-product'
import { Route as ApiPublicLovableSyncPingRouteImport } from './routes/api.public.lovable-sync.ping'
import { Route as ApiPublicBridgeUpdateConfigRouteImport } from './routes/api.public.bridge.update-config'
import { Route as ApiPublicBridgeSyncedProductsRouteImport } from './routes/api.public.bridge.synced-products'
import { Route as ApiPublicBridgeSyncRouteImport } from './routes/api.public.bridge.sync'
import { Route as ApiPublicBridgeShopifyWebhookRouteImport } from './routes/api.public.bridge.shopify-webhook'
import { Route as ApiPublicBridgeReferrerProbeRouteImport } from './routes/api.public.bridge.referrer-probe'
import { Route as ApiPublicBridgePushProductRouteImport } from './routes/api.public.bridge.push-product'
import { Route as ApiPublicBridgeHandshakeRouteImport } from './routes/api.public.bridge.handshake'
import { Route as ApiPublicBridgeGetConfigRouteImport } from './routes/api.public.bridge.get-config'
import { Route as ApiPublicBridgeGenerateCheckoutRouteImport } from './routes/api.public.bridge.generate-checkout'
import { Route as ApiPublicBridgeCronPollRouteImport } from './routes/api.public.bridge.cron-poll'
import { Route as ApiPublicBridgeCronCleanupDraftsRouteImport } from './routes/api.public.bridge.cron-cleanup-drafts'
import { Route as ApiPublicBridgeCheckoutRouteImport } from './routes/api.public.bridge.checkout'
import { Route as ApiPublicBridgeShopifyOauthStartRouteImport } from './routes/api.public.bridge.shopify-oauth.start'
import { Route as ApiPublicBridgeShopifyOauthCallbackRouteImport } from './routes/api.public.bridge.shopify-oauth.callback'

const WashRoute = WashRouteImport.update({
  id: '/wash',
  path: '/wash',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminiRoute = TerminiRouteImport.update({
  id: '/termini',
  path: '/termini',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PonteAdminRoute = PonteAdminRouteImport.update({
  id: '/ponte-admin',
  path: '/ponte-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DeployGuideRoute = DeployGuideRouteImport.update({
  id: '/deploy-guide',
  path: '/deploy-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeAdminRoute = BridgeAdminRouteImport.update({
  id: '/bridge-admin',
  path: '/bridge-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PonteAdminIndexRoute = PonteAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PonteAdminRoute,
} as any)
const ShopSpedizioniRoute = ShopSpedizioniRouteImport.update({
  id: '/shop/spedizioni',
  path: '/shop/spedizioni',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSaleRoute = ShopSaleRouteImport.update({
  id: '/shop/sale',
  path: '/shop/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopResiRoute = ShopResiRouteImport.update({
  id: '/shop/resi',
  path: '/shop/resi',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopFaqRoute = ShopFaqRouteImport.update({
  id: '/shop/faq',
  path: '/shop/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopContattiRoute = ShopContattiRouteImport.update({
  id: '/shop/contatti',
  path: '/shop/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopChiSiamoRoute = ShopChiSiamoRouteImport.update({
  id: '/shop/chi-siamo',
  path: '/shop/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCarrelloRoute = ShopCarrelloRouteImport.update({
  id: '/shop/carrello',
  path: '/shop/carrello',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopAccountRoute = ShopAccountRouteImport.update({
  id: '/shop/account',
  path: '/shop/account',
  getParentRoute: () => rootRouteImport,
} as any)
const PonteAdminWashDebugRoute = PonteAdminWashDebugRouteImport.update({
  id: '/wash-debug',
  path: '/wash-debug',
  getParentRoute: () => PonteAdminRoute,
} as any)
const PonteAdminSyncRoute = PonteAdminSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => PonteAdminRoute,
} as any)
const PonteAdminStoresRoute = PonteAdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => PonteAdminRoute,
} as any)
const PonteAdminSiteSettingsRoute = PonteAdminSiteSettingsRouteImport.update({
  id: '/site-settings',
  path: '/site-settings',
  getParentRoute: () => PonteAdminRoute,
} as any)
const PonteAdminSiteSettingRoute = PonteAdminSiteSettingRouteImport.update({
  id: '/site-setting',
  path: '/site-setting',
  getParentRoute: () => PonteAdminRoute,
} as any)
const PonteAdminShippingRoute = PonteAdminShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => PonteAdminRoute,
} as any)
const PonteAdminRevenueRoute = PonteAdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => PonteAdminRoute,
} as any)
const PonteAdminReferrerCheckRoute = PonteAdminReferrerCheckRouteImport.update({
  id: '/referrer-check',
  path: '/referrer-check',
  getParentRoute: () => PonteAdminRoute,
} as any)
const PonteAdminProdottiRoute = PonteAdminProdottiRouteImport.update({
  id: '/prodotti',
  path: '/prodotti',
  getParentRoute: () => PonteAdminRoute,
} as any)
const PonteAdminNewRoute = PonteAdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PonteAdminRoute,
} as any)
const PonteAdminMigrateSupabaseRoute =
  PonteAdminMigrateSupabaseRouteImport.update({
    id: '/migrate-supabase',
    path: '/migrate-supabase',
    getParentRoute: () => PonteAdminRoute,
  } as any)
const PonteAdminLovableSyncRoute = PonteAdminLovableSyncRouteImport.update({
  id: '/lovable-sync',
  path: '/lovable-sync',
  getParentRoute: () => PonteAdminRoute,
} as any)
const PonteAdminLogsRoute = PonteAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => PonteAdminRoute,
} as any)
const PonteAdminLoginRoute = PonteAdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PonteAdminRoute,
} as any)
const PonteAdminExternalDbRoute = PonteAdminExternalDbRouteImport.update({
  id: '/external-db',
  path: '/external-db',
  getParentRoute: () => PonteAdminRoute,
} as any)
const PonteAdminClonesHealthRoute = PonteAdminClonesHealthRouteImport.update({
  id: '/clones-health',
  path: '/clones-health',
  getParentRoute: () => PonteAdminRoute,
} as any)
const PonteAdminCapiRoute = PonteAdminCapiRouteImport.update({
  id: '/capi',
  path: '/capi',
  getParentRoute: () => PonteAdminRoute,
} as any)
const PonteAdminApplePayRoute = PonteAdminApplePayRouteImport.update({
  id: '/apple-pay',
  path: '/apple-pay',
  getParentRoute: () => PonteAdminRoute,
} as any)
const PonteAdminIdRoute = PonteAdminIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PonteAdminRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeAdminStoresRoute = BridgeAdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => BridgeAdminRoute,
} as any)
const BridgeAdminProdottiRoute = BridgeAdminProdottiRouteImport.update({
  id: '/prodotti',
  path: '/prodotti',
  getParentRoute: () => BridgeAdminRoute,
} as any)
const BridgeAdminLoginRoute = BridgeAdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => BridgeAdminRoute,
} as any)
const ApiGenerateCheckoutRoute = ApiGenerateCheckoutRouteImport.update({
  id: '/api/generate-checkout',
  path: '/api/generate-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute =
  DotwellKnownAppleDeveloperMerchantidDomainAssociationRouteImport.update({
    id: '/.well-known/apple-developer-merchantid-domain-association',
    path: '/.well-known/apple-developer-merchantid-domain-association',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopProdottoSlugRoute = ShopProdottoSlugRouteImport.update({
  id: '/shop/prodotto/$slug',
  path: '/shop/prodotto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCheckoutWhopRoute = ShopCheckoutWhopRouteImport.update({
  id: '/shop/checkout/whop',
  path: '/shop/checkout/whop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCheckoutDemoRoute = ShopCheckoutDemoRouteImport.update({
  id: '/shop/checkout/demo',
  path: '/shop/checkout/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategoriaSlugRoute = ShopCategoriaSlugRouteImport.update({
  id: '/shop/categoria/$slug',
  path: '/shop/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhopWebhookRoute = ApiPublicWhopWebhookRouteImport.update({
  id: '/api/public/whop-webhook',
  path: '/api/public/whop-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncProductRoute = ApiPublicSyncProductRouteImport.update({
  id: '/api/public/sync-product',
  path: '/api/public/sync-product',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyWebhookRoute = ApiPublicShopifyWebhookRouteImport.update({
  id: '/api/public/shopify-webhook',
  path: '/api/public/shopify-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRuntimeSupabaseEnvRoute =
  ApiPublicRuntimeSupabaseEnvRouteImport.update({
    id: '/api/public/runtime-supabase-env',
    path: '/api/public/runtime-supabase-env',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBridgePushShadowProductRoute =
  ApiBridgePushShadowProductRouteImport.update({
    id: '/api/bridge/push-shadow-product',
    path: '/api/bridge/push-shadow-product',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBridgeHandshakeRoute = ApiBridgeHandshakeRouteImport.update({
  id: '/api/bridge/handshake',
  path: '/api/bridge/handshake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLovableSyncPushProductRoute =
  ApiPublicLovableSyncPushProductRouteImport.update({
    id: '/api/public/lovable-sync/push-product',
    path: '/api/public/lovable-sync/push-product',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLovableSyncPingRoute =
  ApiPublicLovableSyncPingRouteImport.update({
    id: '/api/public/lovable-sync/ping',
    path: '/api/public/lovable-sync/ping',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeUpdateConfigRoute =
  ApiPublicBridgeUpdateConfigRouteImport.update({
    id: '/api/public/bridge/update-config',
    path: '/api/public/bridge/update-config',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeSyncedProductsRoute =
  ApiPublicBridgeSyncedProductsRouteImport.update({
    id: '/api/public/bridge/synced-products',
    path: '/api/public/bridge/synced-products',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeSyncRoute = ApiPublicBridgeSyncRouteImport.update({
  id: '/api/public/bridge/sync',
  path: '/api/public/bridge/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeShopifyWebhookRoute =
  ApiPublicBridgeShopifyWebhookRouteImport.update({
    id: '/api/public/bridge/shopify-webhook',
    path: '/api/public/bridge/shopify-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeReferrerProbeRoute =
  ApiPublicBridgeReferrerProbeRouteImport.update({
    id: '/api/public/bridge/referrer-probe',
    path: '/api/public/bridge/referrer-probe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgePushProductRoute =
  ApiPublicBridgePushProductRouteImport.update({
    id: '/api/public/bridge/push-product',
    path: '/api/public/bridge/push-product',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeHandshakeRoute =
  ApiPublicBridgeHandshakeRouteImport.update({
    id: '/api/public/bridge/handshake',
    path: '/api/public/bridge/handshake',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeGetConfigRoute =
  ApiPublicBridgeGetConfigRouteImport.update({
    id: '/api/public/bridge/get-config',
    path: '/api/public/bridge/get-config',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeGenerateCheckoutRoute =
  ApiPublicBridgeGenerateCheckoutRouteImport.update({
    id: '/api/public/bridge/generate-checkout',
    path: '/api/public/bridge/generate-checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeCronPollRoute = ApiPublicBridgeCronPollRouteImport.update({
  id: '/api/public/bridge/cron-poll',
  path: '/api/public/bridge/cron-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeCronCleanupDraftsRoute =
  ApiPublicBridgeCronCleanupDraftsRouteImport.update({
    id: '/api/public/bridge/cron-cleanup-drafts',
    path: '/api/public/bridge/cron-cleanup-drafts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeCheckoutRoute = ApiPublicBridgeCheckoutRouteImport.update({
  id: '/api/public/bridge/checkout',
  path: '/api/public/bridge/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeShopifyOauthStartRoute =
  ApiPublicBridgeShopifyOauthStartRouteImport.update({
    id: '/api/public/bridge/shopify-oauth/start',
    path: '/api/public/bridge/shopify-oauth/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeShopifyOauthCallbackRoute =
  ApiPublicBridgeShopifyOauthCallbackRouteImport.update({
    id: '/api/public/bridge/shopify-oauth/callback',
    path: '/api/public/bridge/shopify-oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bridge-admin': typeof BridgeAdminRouteWithChildren
  '/cookie': typeof CookieRoute
  '/deploy-guide': typeof DeployGuideRoute
  '/ponte-admin': typeof PonteAdminRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/termini': typeof TerminiRoute
  '/wash': typeof WashRoute
  '/.well-known/apple-developer-merchantid-domain-association': typeof DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute
  '/api/$': typeof ApiSplatRoute
  '/api/generate-checkout': typeof ApiGenerateCheckoutRoute
  '/bridge-admin/login': typeof BridgeAdminLoginRoute
  '/bridge-admin/prodotti': typeof BridgeAdminProdottiRoute
  '/bridge-admin/stores': typeof BridgeAdminStoresRoute
  '/p/$slug': typeof PSlugRoute
  '/ponte-admin/$id': typeof PonteAdminIdRoute
  '/ponte-admin/apple-pay': typeof PonteAdminApplePayRoute
  '/ponte-admin/capi': typeof PonteAdminCapiRoute
  '/ponte-admin/clones-health': typeof PonteAdminClonesHealthRoute
  '/ponte-admin/external-db': typeof PonteAdminExternalDbRoute
  '/ponte-admin/login': typeof PonteAdminLoginRoute
  '/ponte-admin/logs': typeof PonteAdminLogsRoute
  '/ponte-admin/lovable-sync': typeof PonteAdminLovableSyncRoute
  '/ponte-admin/migrate-supabase': typeof PonteAdminMigrateSupabaseRoute
  '/ponte-admin/new': typeof PonteAdminNewRoute
  '/ponte-admin/prodotti': typeof PonteAdminProdottiRoute
  '/ponte-admin/referrer-check': typeof PonteAdminReferrerCheckRoute
  '/ponte-admin/revenue': typeof PonteAdminRevenueRoute
  '/ponte-admin/shipping': typeof PonteAdminShippingRoute
  '/ponte-admin/site-setting': typeof PonteAdminSiteSettingRoute
  '/ponte-admin/site-settings': typeof PonteAdminSiteSettingsRoute
  '/ponte-admin/stores': typeof PonteAdminStoresRoute
  '/ponte-admin/sync': typeof PonteAdminSyncRoute
  '/ponte-admin/wash-debug': typeof PonteAdminWashDebugRoute
  '/shop/account': typeof ShopAccountRoute
  '/shop/carrello': typeof ShopCarrelloRoute
  '/shop/chi-siamo': typeof ShopChiSiamoRoute
  '/shop/contatti': typeof ShopContattiRoute
  '/shop/faq': typeof ShopFaqRoute
  '/shop/resi': typeof ShopResiRoute
  '/shop/sale': typeof ShopSaleRoute
  '/shop/spedizioni': typeof ShopSpedizioniRoute
  '/ponte-admin/': typeof PonteAdminIndexRoute
  '/api/bridge/handshake': typeof ApiBridgeHandshakeRoute
  '/api/bridge/push-shadow-product': typeof ApiBridgePushShadowProductRoute
  '/api/public/runtime-supabase-env': typeof ApiPublicRuntimeSupabaseEnvRoute
  '/api/public/shopify-webhook': typeof ApiPublicShopifyWebhookRoute
  '/api/public/sync-product': typeof ApiPublicSyncProductRoute
  '/api/public/whop-webhook': typeof ApiPublicWhopWebhookRoute
  '/shop/categoria/$slug': typeof ShopCategoriaSlugRoute
  '/shop/checkout/demo': typeof ShopCheckoutDemoRoute
  '/shop/checkout/whop': typeof ShopCheckoutWhopRoute
  '/shop/prodotto/$slug': typeof ShopProdottoSlugRoute
  '/api/public/bridge/checkout': typeof ApiPublicBridgeCheckoutRoute
  '/api/public/bridge/cron-cleanup-drafts': typeof ApiPublicBridgeCronCleanupDraftsRoute
  '/api/public/bridge/cron-poll': typeof ApiPublicBridgeCronPollRoute
  '/api/public/bridge/generate-checkout': typeof ApiPublicBridgeGenerateCheckoutRoute
  '/api/public/bridge/get-config': typeof ApiPublicBridgeGetConfigRoute
  '/api/public/bridge/handshake': typeof ApiPublicBridgeHandshakeRoute
  '/api/public/bridge/push-product': typeof ApiPublicBridgePushProductRoute
  '/api/public/bridge/referrer-probe': typeof ApiPublicBridgeReferrerProbeRoute
  '/api/public/bridge/shopify-webhook': typeof ApiPublicBridgeShopifyWebhookRoute
  '/api/public/bridge/sync': typeof ApiPublicBridgeSyncRoute
  '/api/public/bridge/synced-products': typeof ApiPublicBridgeSyncedProductsRoute
  '/api/public/bridge/update-config': typeof ApiPublicBridgeUpdateConfigRoute
  '/api/public/lovable-sync/ping': typeof ApiPublicLovableSyncPingRoute
  '/api/public/lovable-sync/push-product': typeof ApiPublicLovableSyncPushProductRoute
  '/api/public/bridge/shopify-oauth/callback': typeof ApiPublicBridgeShopifyOauthCallbackRoute
  '/api/public/bridge/shopify-oauth/start': typeof ApiPublicBridgeShopifyOauthStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bridge-admin': typeof BridgeAdminRouteWithChildren
  '/cookie': typeof CookieRoute
  '/deploy-guide': typeof DeployGuideRoute
  '/privacy': typeof PrivacyRoute
  '/termini': typeof TerminiRoute
  '/wash': typeof WashRoute
  '/.well-known/apple-developer-merchantid-domain-association': typeof DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute
  '/api/$': typeof ApiSplatRoute
  '/api/generate-checkout': typeof ApiGenerateCheckoutRoute
  '/bridge-admin/login': typeof BridgeAdminLoginRoute
  '/bridge-admin/prodotti': typeof BridgeAdminProdottiRoute
  '/bridge-admin/stores': typeof BridgeAdminStoresRoute
  '/p/$slug': typeof PSlugRoute
  '/ponte-admin/$id': typeof PonteAdminIdRoute
  '/ponte-admin/apple-pay': typeof PonteAdminApplePayRoute
  '/ponte-admin/capi': typeof PonteAdminCapiRoute
  '/ponte-admin/clones-health': typeof PonteAdminClonesHealthRoute
  '/ponte-admin/external-db': typeof PonteAdminExternalDbRoute
  '/ponte-admin/login': typeof PonteAdminLoginRoute
  '/ponte-admin/logs': typeof PonteAdminLogsRoute
  '/ponte-admin/lovable-sync': typeof PonteAdminLovableSyncRoute
  '/ponte-admin/migrate-supabase': typeof PonteAdminMigrateSupabaseRoute
  '/ponte-admin/new': typeof PonteAdminNewRoute
  '/ponte-admin/prodotti': typeof PonteAdminProdottiRoute
  '/ponte-admin/referrer-check': typeof PonteAdminReferrerCheckRoute
  '/ponte-admin/revenue': typeof PonteAdminRevenueRoute
  '/ponte-admin/shipping': typeof PonteAdminShippingRoute
  '/ponte-admin/site-setting': typeof PonteAdminSiteSettingRoute
  '/ponte-admin/site-settings': typeof PonteAdminSiteSettingsRoute
  '/ponte-admin/stores': typeof PonteAdminStoresRoute
  '/ponte-admin/sync': typeof PonteAdminSyncRoute
  '/ponte-admin/wash-debug': typeof PonteAdminWashDebugRoute
  '/shop/account': typeof ShopAccountRoute
  '/shop/carrello': typeof ShopCarrelloRoute
  '/shop/chi-siamo': typeof ShopChiSiamoRoute
  '/shop/contatti': typeof ShopContattiRoute
  '/shop/faq': typeof ShopFaqRoute
  '/shop/resi': typeof ShopResiRoute
  '/shop/sale': typeof ShopSaleRoute
  '/shop/spedizioni': typeof ShopSpedizioniRoute
  '/ponte-admin': typeof PonteAdminIndexRoute
  '/api/bridge/handshake': typeof ApiBridgeHandshakeRoute
  '/api/bridge/push-shadow-product': typeof ApiBridgePushShadowProductRoute
  '/api/public/runtime-supabase-env': typeof ApiPublicRuntimeSupabaseEnvRoute
  '/api/public/shopify-webhook': typeof ApiPublicShopifyWebhookRoute
  '/api/public/sync-product': typeof ApiPublicSyncProductRoute
  '/api/public/whop-webhook': typeof ApiPublicWhopWebhookRoute
  '/shop/categoria/$slug': typeof ShopCategoriaSlugRoute
  '/shop/checkout/demo': typeof ShopCheckoutDemoRoute
  '/shop/checkout/whop': typeof ShopCheckoutWhopRoute
  '/shop/prodotto/$slug': typeof ShopProdottoSlugRoute
  '/api/public/bridge/checkout': typeof ApiPublicBridgeCheckoutRoute
  '/api/public/bridge/cron-cleanup-drafts': typeof ApiPublicBridgeCronCleanupDraftsRoute
  '/api/public/bridge/cron-poll': typeof ApiPublicBridgeCronPollRoute
  '/api/public/bridge/generate-checkout': typeof ApiPublicBridgeGenerateCheckoutRoute
  '/api/public/bridge/get-config': typeof ApiPublicBridgeGetConfigRoute
  '/api/public/bridge/handshake': typeof ApiPublicBridgeHandshakeRoute
  '/api/public/bridge/push-product': typeof ApiPublicBridgePushProductRoute
  '/api/public/bridge/referrer-probe': typeof ApiPublicBridgeReferrerProbeRoute
  '/api/public/bridge/shopify-webhook': typeof ApiPublicBridgeShopifyWebhookRoute
  '/api/public/bridge/sync': typeof ApiPublicBridgeSyncRoute
  '/api/public/bridge/synced-products': typeof ApiPublicBridgeSyncedProductsRoute
  '/api/public/bridge/update-config': typeof ApiPublicBridgeUpdateConfigRoute
  '/api/public/lovable-sync/ping': typeof ApiPublicLovableSyncPingRoute
  '/api/public/lovable-sync/push-product': typeof ApiPublicLovableSyncPushProductRoute
  '/api/public/bridge/shopify-oauth/callback': typeof ApiPublicBridgeShopifyOauthCallbackRoute
  '/api/public/bridge/shopify-oauth/start': typeof ApiPublicBridgeShopifyOauthStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bridge-admin': typeof BridgeAdminRouteWithChildren
  '/cookie': typeof CookieRoute
  '/deploy-guide': typeof DeployGuideRoute
  '/ponte-admin': typeof PonteAdminRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/termini': typeof TerminiRoute
  '/wash': typeof WashRoute
  '/.well-known/apple-developer-merchantid-domain-association': typeof DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute
  '/api/$': typeof ApiSplatRoute
  '/api/generate-checkout': typeof ApiGenerateCheckoutRoute
  '/bridge-admin/login': typeof BridgeAdminLoginRoute
  '/bridge-admin/prodotti': typeof BridgeAdminProdottiRoute
  '/bridge-admin/stores': typeof BridgeAdminStoresRoute
  '/p/$slug': typeof PSlugRoute
  '/ponte-admin/$id': typeof PonteAdminIdRoute
  '/ponte-admin/apple-pay': typeof PonteAdminApplePayRoute
  '/ponte-admin/capi': typeof PonteAdminCapiRoute
  '/ponte-admin/clones-health': typeof PonteAdminClonesHealthRoute
  '/ponte-admin/external-db': typeof PonteAdminExternalDbRoute
  '/ponte-admin/login': typeof PonteAdminLoginRoute
  '/ponte-admin/logs': typeof PonteAdminLogsRoute
  '/ponte-admin/lovable-sync': typeof PonteAdminLovableSyncRoute
  '/ponte-admin/migrate-supabase': typeof PonteAdminMigrateSupabaseRoute
  '/ponte-admin/new': typeof PonteAdminNewRoute
  '/ponte-admin/prodotti': typeof PonteAdminProdottiRoute
  '/ponte-admin/referrer-check': typeof PonteAdminReferrerCheckRoute
  '/ponte-admin/revenue': typeof PonteAdminRevenueRoute
  '/ponte-admin/shipping': typeof PonteAdminShippingRoute
  '/ponte-admin/site-setting': typeof PonteAdminSiteSettingRoute
  '/ponte-admin/site-settings': typeof PonteAdminSiteSettingsRoute
  '/ponte-admin/stores': typeof PonteAdminStoresRoute
  '/ponte-admin/sync': typeof PonteAdminSyncRoute
  '/ponte-admin/wash-debug': typeof PonteAdminWashDebugRoute
  '/shop/account': typeof ShopAccountRoute
  '/shop/carrello': typeof ShopCarrelloRoute
  '/shop/chi-siamo': typeof ShopChiSiamoRoute
  '/shop/contatti': typeof ShopContattiRoute
  '/shop/faq': typeof ShopFaqRoute
  '/shop/resi': typeof ShopResiRoute
  '/shop/sale': typeof ShopSaleRoute
  '/shop/spedizioni': typeof ShopSpedizioniRoute
  '/ponte-admin/': typeof PonteAdminIndexRoute
  '/api/bridge/handshake': typeof ApiBridgeHandshakeRoute
  '/api/bridge/push-shadow-product': typeof ApiBridgePushShadowProductRoute
  '/api/public/runtime-supabase-env': typeof ApiPublicRuntimeSupabaseEnvRoute
  '/api/public/shopify-webhook': typeof ApiPublicShopifyWebhookRoute
  '/api/public/sync-product': typeof ApiPublicSyncProductRoute
  '/api/public/whop-webhook': typeof ApiPublicWhopWebhookRoute
  '/shop/categoria/$slug': typeof ShopCategoriaSlugRoute
  '/shop/checkout/demo': typeof ShopCheckoutDemoRoute
  '/shop/checkout/whop': typeof ShopCheckoutWhopRoute
  '/shop/prodotto/$slug': typeof ShopProdottoSlugRoute
  '/api/public/bridge/checkout': typeof ApiPublicBridgeCheckoutRoute
  '/api/public/bridge/cron-cleanup-drafts': typeof ApiPublicBridgeCronCleanupDraftsRoute
  '/api/public/bridge/cron-poll': typeof ApiPublicBridgeCronPollRoute
  '/api/public/bridge/generate-checkout': typeof ApiPublicBridgeGenerateCheckoutRoute
  '/api/public/bridge/get-config': typeof ApiPublicBridgeGetConfigRoute
  '/api/public/bridge/handshake': typeof ApiPublicBridgeHandshakeRoute
  '/api/public/bridge/push-product': typeof ApiPublicBridgePushProductRoute
  '/api/public/bridge/referrer-probe': typeof ApiPublicBridgeReferrerProbeRoute
  '/api/public/bridge/shopify-webhook': typeof ApiPublicBridgeShopifyWebhookRoute
  '/api/public/bridge/sync': typeof ApiPublicBridgeSyncRoute
  '/api/public/bridge/synced-products': typeof ApiPublicBridgeSyncedProductsRoute
  '/api/public/bridge/update-config': typeof ApiPublicBridgeUpdateConfigRoute
  '/api/public/lovable-sync/ping': typeof ApiPublicLovableSyncPingRoute
  '/api/public/lovable-sync/push-product': typeof ApiPublicLovableSyncPushProductRoute
  '/api/public/bridge/shopify-oauth/callback': typeof ApiPublicBridgeShopifyOauthCallbackRoute
  '/api/public/bridge/shopify-oauth/start': typeof ApiPublicBridgeShopifyOauthStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bridge-admin'
    | '/cookie'
    | '/deploy-guide'
    | '/ponte-admin'
    | '/privacy'
    | '/termini'
    | '/wash'
    | '/.well-known/apple-developer-merchantid-domain-association'
    | '/api/$'
    | '/api/generate-checkout'
    | '/bridge-admin/login'
    | '/bridge-admin/prodotti'
    | '/bridge-admin/stores'
    | '/p/$slug'
    | '/ponte-admin/$id'
    | '/ponte-admin/apple-pay'
    | '/ponte-admin/capi'
    | '/ponte-admin/clones-health'
    | '/ponte-admin/external-db'
    | '/ponte-admin/login'
    | '/ponte-admin/logs'
    | '/ponte-admin/lovable-sync'
    | '/ponte-admin/migrate-supabase'
    | '/ponte-admin/new'
    | '/ponte-admin/prodotti'
    | '/ponte-admin/referrer-check'
    | '/ponte-admin/revenue'
    | '/ponte-admin/shipping'
    | '/ponte-admin/site-setting'
    | '/ponte-admin/site-settings'
    | '/ponte-admin/stores'
    | '/ponte-admin/sync'
    | '/ponte-admin/wash-debug'
    | '/shop/account'
    | '/shop/carrello'
    | '/shop/chi-siamo'
    | '/shop/contatti'
    | '/shop/faq'
    | '/shop/resi'
    | '/shop/sale'
    | '/shop/spedizioni'
    | '/ponte-admin/'
    | '/api/bridge/handshake'
    | '/api/bridge/push-shadow-product'
    | '/api/public/runtime-supabase-env'
    | '/api/public/shopify-webhook'
    | '/api/public/sync-product'
    | '/api/public/whop-webhook'
    | '/shop/categoria/$slug'
    | '/shop/checkout/demo'
    | '/shop/checkout/whop'
    | '/shop/prodotto/$slug'
    | '/api/public/bridge/checkout'
    | '/api/public/bridge/cron-cleanup-drafts'
    | '/api/public/bridge/cron-poll'
    | '/api/public/bridge/generate-checkout'
    | '/api/public/bridge/get-config'
    | '/api/public/bridge/handshake'
    | '/api/public/bridge/push-product'
    | '/api/public/bridge/referrer-probe'
    | '/api/public/bridge/shopify-webhook'
    | '/api/public/bridge/sync'
    | '/api/public/bridge/synced-products'
    | '/api/public/bridge/update-config'
    | '/api/public/lovable-sync/ping'
    | '/api/public/lovable-sync/push-product'
    | '/api/public/bridge/shopify-oauth/callback'
    | '/api/public/bridge/shopify-oauth/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bridge-admin'
    | '/cookie'
    | '/deploy-guide'
    | '/privacy'
    | '/termini'
    | '/wash'
    | '/.well-known/apple-developer-merchantid-domain-association'
    | '/api/$'
    | '/api/generate-checkout'
    | '/bridge-admin/login'
    | '/bridge-admin/prodotti'
    | '/bridge-admin/stores'
    | '/p/$slug'
    | '/ponte-admin/$id'
    | '/ponte-admin/apple-pay'
    | '/ponte-admin/capi'
    | '/ponte-admin/clones-health'
    | '/ponte-admin/external-db'
    | '/ponte-admin/login'
    | '/ponte-admin/logs'
    | '/ponte-admin/lovable-sync'
    | '/ponte-admin/migrate-supabase'
    | '/ponte-admin/new'
    | '/ponte-admin/prodotti'
    | '/ponte-admin/referrer-check'
    | '/ponte-admin/revenue'
    | '/ponte-admin/shipping'
    | '/ponte-admin/site-setting'
    | '/ponte-admin/site-settings'
    | '/ponte-admin/stores'
    | '/ponte-admin/sync'
    | '/ponte-admin/wash-debug'
    | '/shop/account'
    | '/shop/carrello'
    | '/shop/chi-siamo'
    | '/shop/contatti'
    | '/shop/faq'
    | '/shop/resi'
    | '/shop/sale'
    | '/shop/spedizioni'
    | '/ponte-admin'
    | '/api/bridge/handshake'
    | '/api/bridge/push-shadow-product'
    | '/api/public/runtime-supabase-env'
    | '/api/public/shopify-webhook'
    | '/api/public/sync-product'
    | '/api/public/whop-webhook'
    | '/shop/categoria/$slug'
    | '/shop/checkout/demo'
    | '/shop/checkout/whop'
    | '/shop/prodotto/$slug'
    | '/api/public/bridge/checkout'
    | '/api/public/bridge/cron-cleanup-drafts'
    | '/api/public/bridge/cron-poll'
    | '/api/public/bridge/generate-checkout'
    | '/api/public/bridge/get-config'
    | '/api/public/bridge/handshake'
    | '/api/public/bridge/push-product'
    | '/api/public/bridge/referrer-probe'
    | '/api/public/bridge/shopify-webhook'
    | '/api/public/bridge/sync'
    | '/api/public/bridge/synced-products'
    | '/api/public/bridge/update-config'
    | '/api/public/lovable-sync/ping'
    | '/api/public/lovable-sync/push-product'
    | '/api/public/bridge/shopify-oauth/callback'
    | '/api/public/bridge/shopify-oauth/start'
  id:
    | '__root__'
    | '/'
    | '/bridge-admin'
    | '/cookie'
    | '/deploy-guide'
    | '/ponte-admin'
    | '/privacy'
    | '/termini'
    | '/wash'
    | '/.well-known/apple-developer-merchantid-domain-association'
    | '/api/$'
    | '/api/generate-checkout'
    | '/bridge-admin/login'
    | '/bridge-admin/prodotti'
    | '/bridge-admin/stores'
    | '/p/$slug'
    | '/ponte-admin/$id'
    | '/ponte-admin/apple-pay'
    | '/ponte-admin/capi'
    | '/ponte-admin/clones-health'
    | '/ponte-admin/external-db'
    | '/ponte-admin/login'
    | '/ponte-admin/logs'
    | '/ponte-admin/lovable-sync'
    | '/ponte-admin/migrate-supabase'
    | '/ponte-admin/new'
    | '/ponte-admin/prodotti'
    | '/ponte-admin/referrer-check'
    | '/ponte-admin/revenue'
    | '/ponte-admin/shipping'
    | '/ponte-admin/site-setting'
    | '/ponte-admin/site-settings'
    | '/ponte-admin/stores'
    | '/ponte-admin/sync'
    | '/ponte-admin/wash-debug'
    | '/shop/account'
    | '/shop/carrello'
    | '/shop/chi-siamo'
    | '/shop/contatti'
    | '/shop/faq'
    | '/shop/resi'
    | '/shop/sale'
    | '/shop/spedizioni'
    | '/ponte-admin/'
    | '/api/bridge/handshake'
    | '/api/bridge/push-shadow-product'
    | '/api/public/runtime-supabase-env'
    | '/api/public/shopify-webhook'
    | '/api/public/sync-product'
    | '/api/public/whop-webhook'
    | '/shop/categoria/$slug'
    | '/shop/checkout/demo'
    | '/shop/checkout/whop'
    | '/shop/prodotto/$slug'
    | '/api/public/bridge/checkout'
    | '/api/public/bridge/cron-cleanup-drafts'
    | '/api/public/bridge/cron-poll'
    | '/api/public/bridge/generate-checkout'
    | '/api/public/bridge/get-config'
    | '/api/public/bridge/handshake'
    | '/api/public/bridge/push-product'
    | '/api/public/bridge/referrer-probe'
    | '/api/public/bridge/shopify-webhook'
    | '/api/public/bridge/sync'
    | '/api/public/bridge/synced-products'
    | '/api/public/bridge/update-config'
    | '/api/public/lovable-sync/ping'
    | '/api/public/lovable-sync/push-product'
    | '/api/public/bridge/shopify-oauth/callback'
    | '/api/public/bridge/shopify-oauth/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BridgeAdminRoute: typeof BridgeAdminRouteWithChildren
  CookieRoute: typeof CookieRoute
  DeployGuideRoute: typeof DeployGuideRoute
  PonteAdminRoute: typeof PonteAdminRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TerminiRoute: typeof TerminiRoute
  WashRoute: typeof WashRoute
  DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute: typeof DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiGenerateCheckoutRoute: typeof ApiGenerateCheckoutRoute
  PSlugRoute: typeof PSlugRoute
  ShopAccountRoute: typeof ShopAccountRoute
  ShopCarrelloRoute: typeof ShopCarrelloRoute
  ShopChiSiamoRoute: typeof ShopChiSiamoRoute
  ShopContattiRoute: typeof ShopContattiRoute
  ShopFaqRoute: typeof ShopFaqRoute
  ShopResiRoute: typeof ShopResiRoute
  ShopSaleRoute: typeof ShopSaleRoute
  ShopSpedizioniRoute: typeof ShopSpedizioniRoute
  ApiBridgeHandshakeRoute: typeof ApiBridgeHandshakeRoute
  ApiBridgePushShadowProductRoute: typeof ApiBridgePushShadowProductRoute
  ApiPublicRuntimeSupabaseEnvRoute: typeof ApiPublicRuntimeSupabaseEnvRoute
  ApiPublicShopifyWebhookRoute: typeof ApiPublicShopifyWebhookRoute
  ApiPublicSyncProductRoute: typeof ApiPublicSyncProductRoute
  ApiPublicWhopWebhookRoute: typeof ApiPublicWhopWebhookRoute
  ShopCategoriaSlugRoute: typeof ShopCategoriaSlugRoute
  ShopCheckoutDemoRoute: typeof ShopCheckoutDemoRoute
  ShopCheckoutWhopRoute: typeof ShopCheckoutWhopRoute
  ShopProdottoSlugRoute: typeof ShopProdottoSlugRoute
  ApiPublicBridgeCheckoutRoute: typeof ApiPublicBridgeCheckoutRoute
  ApiPublicBridgeCronCleanupDraftsRoute: typeof ApiPublicBridgeCronCleanupDraftsRoute
  ApiPublicBridgeCronPollRoute: typeof ApiPublicBridgeCronPollRoute
  ApiPublicBridgeGenerateCheckoutRoute: typeof ApiPublicBridgeGenerateCheckoutRoute
  ApiPublicBridgeGetConfigRoute: typeof ApiPublicBridgeGetConfigRoute
  ApiPublicBridgeHandshakeRoute: typeof ApiPublicBridgeHandshakeRoute
  ApiPublicBridgePushProductRoute: typeof ApiPublicBridgePushProductRoute
  ApiPublicBridgeReferrerProbeRoute: typeof ApiPublicBridgeReferrerProbeRoute
  ApiPublicBridgeShopifyWebhookRoute: typeof ApiPublicBridgeShopifyWebhookRoute
  ApiPublicBridgeSyncRoute: typeof ApiPublicBridgeSyncRoute
  ApiPublicBridgeSyncedProductsRoute: typeof ApiPublicBridgeSyncedProductsRoute
  ApiPublicBridgeUpdateConfigRoute: typeof ApiPublicBridgeUpdateConfigRoute
  ApiPublicLovableSyncPingRoute: typeof ApiPublicLovableSyncPingRoute
  ApiPublicLovableSyncPushProductRoute: typeof ApiPublicLovableSyncPushProductRoute
  ApiPublicBridgeShopifyOauthCallbackRoute: typeof ApiPublicBridgeShopifyOauthCallbackRoute
  ApiPublicBridgeShopifyOauthStartRoute: typeof ApiPublicBridgeShopifyOauthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wash': {
      id: '/wash'
      path: '/wash'
      fullPath: '/wash'
      preLoaderRoute: typeof WashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termini': {
      id: '/termini'
      path: '/termini'
      fullPath: '/termini'
      preLoaderRoute: typeof TerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponte-admin': {
      id: '/ponte-admin'
      path: '/ponte-admin'
      fullPath: '/ponte-admin'
      preLoaderRoute: typeof PonteAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy-guide': {
      id: '/deploy-guide'
      path: '/deploy-guide'
      fullPath: '/deploy-guide'
      preLoaderRoute: typeof DeployGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge-admin': {
      id: '/bridge-admin'
      path: '/bridge-admin'
      fullPath: '/bridge-admin'
      preLoaderRoute: typeof BridgeAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponte-admin/': {
      id: '/ponte-admin/'
      path: '/'
      fullPath: '/ponte-admin/'
      preLoaderRoute: typeof PonteAdminIndexRouteImport
      parentRoute: typeof PonteAdminRoute
    }
    '/shop/spedizioni': {
      id: '/shop/spedizioni'
      path: '/shop/spedizioni'
      fullPath: '/shop/spedizioni'
      preLoaderRoute: typeof ShopSpedizioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/sale': {
      id: '/shop/sale'
      path: '/shop/sale'
      fullPath: '/shop/sale'
      preLoaderRoute: typeof ShopSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/resi': {
      id: '/shop/resi'
      path: '/shop/resi'
      fullPath: '/shop/resi'
      preLoaderRoute: typeof ShopResiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/faq': {
      id: '/shop/faq'
      path: '/shop/faq'
      fullPath: '/shop/faq'
      preLoaderRoute: typeof ShopFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/contatti': {
      id: '/shop/contatti'
      path: '/shop/contatti'
      fullPath: '/shop/contatti'
      preLoaderRoute: typeof ShopContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/chi-siamo': {
      id: '/shop/chi-siamo'
      path: '/shop/chi-siamo'
      fullPath: '/shop/chi-siamo'
      preLoaderRoute: typeof ShopChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/carrello': {
      id: '/shop/carrello'
      path: '/shop/carrello'
      fullPath: '/shop/carrello'
      preLoaderRoute: typeof ShopCarrelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/account': {
      id: '/shop/account'
      path: '/shop/account'
      fullPath: '/shop/account'
      preLoaderRoute: typeof ShopAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponte-admin/wash-debug': {
      id: '/ponte-admin/wash-debug'
      path: '/wash-debug'
      fullPath: '/ponte-admin/wash-debug'
      preLoaderRoute: typeof PonteAdminWashDebugRouteImport
      parentRoute: typeof PonteAdminRoute
    }
    '/ponte-admin/sync': {
      id: '/ponte-admin/sync'
      path: '/sync'
      fullPath: '/ponte-admin/sync'
      preLoaderRoute: typeof PonteAdminSyncRouteImport
      parentRoute: typeof PonteAdminRoute
    }
    '/ponte-admin/stores': {
      id: '/ponte-admin/stores'
      path: '/stores'
      fullPath: '/ponte-admin/stores'
      preLoaderRoute: typeof PonteAdminStoresRouteImport
      parentRoute: typeof PonteAdminRoute
    }
    '/ponte-admin/site-settings': {
      id: '/ponte-admin/site-settings'
      path: '/site-settings'
      fullPath: '/ponte-admin/site-settings'
      preLoaderRoute: typeof PonteAdminSiteSettingsRouteImport
      parentRoute: typeof PonteAdminRoute
    }
    '/ponte-admin/site-setting': {
      id: '/ponte-admin/site-setting'
      path: '/site-setting'
      fullPath: '/ponte-admin/site-setting'
      preLoaderRoute: typeof PonteAdminSiteSettingRouteImport
      parentRoute: typeof PonteAdminRoute
    }
    '/ponte-admin/shipping': {
      id: '/ponte-admin/shipping'
      path: '/shipping'
      fullPath: '/ponte-admin/shipping'
      preLoaderRoute: typeof PonteAdminShippingRouteImport
      parentRoute: typeof PonteAdminRoute
    }
    '/ponte-admin/revenue': {
      id: '/ponte-admin/revenue'
      path: '/revenue'
      fullPath: '/ponte-admin/revenue'
      preLoaderRoute: typeof PonteAdminRevenueRouteImport
      parentRoute: typeof PonteAdminRoute
    }
    '/ponte-admin/referrer-check': {
      id: '/ponte-admin/referrer-check'
      path: '/referrer-check'
      fullPath: '/ponte-admin/referrer-check'
      preLoaderRoute: typeof PonteAdminReferrerCheckRouteImport
      parentRoute: typeof PonteAdminRoute
    }
    '/ponte-admin/prodotti': {
      id: '/ponte-admin/prodotti'
      path: '/prodotti'
      fullPath: '/ponte-admin/prodotti'
      preLoaderRoute: typeof PonteAdminProdottiRouteImport
      parentRoute: typeof PonteAdminRoute
    }
    '/ponte-admin/new': {
      id: '/ponte-admin/new'
      path: '/new'
      fullPath: '/ponte-admin/new'
      preLoaderRoute: typeof PonteAdminNewRouteImport
      parentRoute: typeof PonteAdminRoute
    }
    '/ponte-admin/migrate-supabase': {
      id: '/ponte-admin/migrate-supabase'
      path: '/migrate-supabase'
      fullPath: '/ponte-admin/migrate-supabase'
      preLoaderRoute: typeof PonteAdminMigrateSupabaseRouteImport
      parentRoute: typeof PonteAdminRoute
    }
    '/ponte-admin/lovable-sync': {
      id: '/ponte-admin/lovable-sync'
      path: '/lovable-sync'
      fullPath: '/ponte-admin/lovable-sync'
      preLoaderRoute: typeof PonteAdminLovableSyncRouteImport
      parentRoute: typeof PonteAdminRoute
    }
    '/ponte-admin/logs': {
      id: '/ponte-admin/logs'
      path: '/logs'
      fullPath: '/ponte-admin/logs'
      preLoaderRoute: typeof PonteAdminLogsRouteImport
      parentRoute: typeof PonteAdminRoute
    }
    '/ponte-admin/login': {
      id: '/ponte-admin/login'
      path: '/login'
      fullPath: '/ponte-admin/login'
      preLoaderRoute: typeof PonteAdminLoginRouteImport
      parentRoute: typeof PonteAdminRoute
    }
    '/ponte-admin/external-db': {
      id: '/ponte-admin/external-db'
      path: '/external-db'
      fullPath: '/ponte-admin/external-db'
      preLoaderRoute: typeof PonteAdminExternalDbRouteImport
      parentRoute: typeof PonteAdminRoute
    }
    '/ponte-admin/clones-health': {
      id: '/ponte-admin/clones-health'
      path: '/clones-health'
      fullPath: '/ponte-admin/clones-health'
      preLoaderRoute: typeof PonteAdminClonesHealthRouteImport
      parentRoute: typeof PonteAdminRoute
    }
    '/ponte-admin/capi': {
      id: '/ponte-admin/capi'
      path: '/capi'
      fullPath: '/ponte-admin/capi'
      preLoaderRoute: typeof PonteAdminCapiRouteImport
      parentRoute: typeof PonteAdminRoute
    }
    '/ponte-admin/apple-pay': {
      id: '/ponte-admin/apple-pay'
      path: '/apple-pay'
      fullPath: '/ponte-admin/apple-pay'
      preLoaderRoute: typeof PonteAdminApplePayRouteImport
      parentRoute: typeof PonteAdminRoute
    }
    '/ponte-admin/$id': {
      id: '/ponte-admin/$id'
      path: '/$id'
      fullPath: '/ponte-admin/$id'
      preLoaderRoute: typeof PonteAdminIdRouteImport
      parentRoute: typeof PonteAdminRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge-admin/stores': {
      id: '/bridge-admin/stores'
      path: '/stores'
      fullPath: '/bridge-admin/stores'
      preLoaderRoute: typeof BridgeAdminStoresRouteImport
      parentRoute: typeof BridgeAdminRoute
    }
    '/bridge-admin/prodotti': {
      id: '/bridge-admin/prodotti'
      path: '/prodotti'
      fullPath: '/bridge-admin/prodotti'
      preLoaderRoute: typeof BridgeAdminProdottiRouteImport
      parentRoute: typeof BridgeAdminRoute
    }
    '/bridge-admin/login': {
      id: '/bridge-admin/login'
      path: '/login'
      fullPath: '/bridge-admin/login'
      preLoaderRoute: typeof BridgeAdminLoginRouteImport
      parentRoute: typeof BridgeAdminRoute
    }
    '/api/generate-checkout': {
      id: '/api/generate-checkout'
      path: '/api/generate-checkout'
      fullPath: '/api/generate-checkout'
      preLoaderRoute: typeof ApiGenerateCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/apple-developer-merchantid-domain-association': {
      id: '/.well-known/apple-developer-merchantid-domain-association'
      path: '/.well-known/apple-developer-merchantid-domain-association'
      fullPath: '/.well-known/apple-developer-merchantid-domain-association'
      preLoaderRoute: typeof DotwellKnownAppleDeveloperMerchantidDomainAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/prodotto/$slug': {
      id: '/shop/prodotto/$slug'
      path: '/shop/prodotto/$slug'
      fullPath: '/shop/prodotto/$slug'
      preLoaderRoute: typeof ShopProdottoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/checkout/whop': {
      id: '/shop/checkout/whop'
      path: '/shop/checkout/whop'
      fullPath: '/shop/checkout/whop'
      preLoaderRoute: typeof ShopCheckoutWhopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/checkout/demo': {
      id: '/shop/checkout/demo'
      path: '/shop/checkout/demo'
      fullPath: '/shop/checkout/demo'
      preLoaderRoute: typeof ShopCheckoutDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/categoria/$slug': {
      id: '/shop/categoria/$slug'
      path: '/shop/categoria/$slug'
      fullPath: '/shop/categoria/$slug'
      preLoaderRoute: typeof ShopCategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whop-webhook': {
      id: '/api/public/whop-webhook'
      path: '/api/public/whop-webhook'
      fullPath: '/api/public/whop-webhook'
      preLoaderRoute: typeof ApiPublicWhopWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-product': {
      id: '/api/public/sync-product'
      path: '/api/public/sync-product'
      fullPath: '/api/public/sync-product'
      preLoaderRoute: typeof ApiPublicSyncProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify-webhook': {
      id: '/api/public/shopify-webhook'
      path: '/api/public/shopify-webhook'
      fullPath: '/api/public/shopify-webhook'
      preLoaderRoute: typeof ApiPublicShopifyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/runtime-supabase-env': {
      id: '/api/public/runtime-supabase-env'
      path: '/api/public/runtime-supabase-env'
      fullPath: '/api/public/runtime-supabase-env'
      preLoaderRoute: typeof ApiPublicRuntimeSupabaseEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge/push-shadow-product': {
      id: '/api/bridge/push-shadow-product'
      path: '/api/bridge/push-shadow-product'
      fullPath: '/api/bridge/push-shadow-product'
      preLoaderRoute: typeof ApiBridgePushShadowProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge/handshake': {
      id: '/api/bridge/handshake'
      path: '/api/bridge/handshake'
      fullPath: '/api/bridge/handshake'
      preLoaderRoute: typeof ApiBridgeHandshakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lovable-sync/push-product': {
      id: '/api/public/lovable-sync/push-product'
      path: '/api/public/lovable-sync/push-product'
      fullPath: '/api/public/lovable-sync/push-product'
      preLoaderRoute: typeof ApiPublicLovableSyncPushProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lovable-sync/ping': {
      id: '/api/public/lovable-sync/ping'
      path: '/api/public/lovable-sync/ping'
      fullPath: '/api/public/lovable-sync/ping'
      preLoaderRoute: typeof ApiPublicLovableSyncPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/update-config': {
      id: '/api/public/bridge/update-config'
      path: '/api/public/bridge/update-config'
      fullPath: '/api/public/bridge/update-config'
      preLoaderRoute: typeof ApiPublicBridgeUpdateConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/synced-products': {
      id: '/api/public/bridge/synced-products'
      path: '/api/public/bridge/synced-products'
      fullPath: '/api/public/bridge/synced-products'
      preLoaderRoute: typeof ApiPublicBridgeSyncedProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/sync': {
      id: '/api/public/bridge/sync'
      path: '/api/public/bridge/sync'
      fullPath: '/api/public/bridge/sync'
      preLoaderRoute: typeof ApiPublicBridgeSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/shopify-webhook': {
      id: '/api/public/bridge/shopify-webhook'
      path: '/api/public/bridge/shopify-webhook'
      fullPath: '/api/public/bridge/shopify-webhook'
      preLoaderRoute: typeof ApiPublicBridgeShopifyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/referrer-probe': {
      id: '/api/public/bridge/referrer-probe'
      path: '/api/public/bridge/referrer-probe'
      fullPath: '/api/public/bridge/referrer-probe'
      preLoaderRoute: typeof ApiPublicBridgeReferrerProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/push-product': {
      id: '/api/public/bridge/push-product'
      path: '/api/public/bridge/push-product'
      fullPath: '/api/public/bridge/push-product'
      preLoaderRoute: typeof ApiPublicBridgePushProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/handshake': {
      id: '/api/public/bridge/handshake'
      path: '/api/public/bridge/handshake'
      fullPath: '/api/public/bridge/handshake'
      preLoaderRoute: typeof ApiPublicBridgeHandshakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/get-config': {
      id: '/api/public/bridge/get-config'
      path: '/api/public/bridge/get-config'
      fullPath: '/api/public/bridge/get-config'
      preLoaderRoute: typeof ApiPublicBridgeGetConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/generate-checkout': {
      id: '/api/public/bridge/generate-checkout'
      path: '/api/public/bridge/generate-checkout'
      fullPath: '/api/public/bridge/generate-checkout'
      preLoaderRoute: typeof ApiPublicBridgeGenerateCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/cron-poll': {
      id: '/api/public/bridge/cron-poll'
      path: '/api/public/bridge/cron-poll'
      fullPath: '/api/public/bridge/cron-poll'
      preLoaderRoute: typeof ApiPublicBridgeCronPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/cron-cleanup-drafts': {
      id: '/api/public/bridge/cron-cleanup-drafts'
      path: '/api/public/bridge/cron-cleanup-drafts'
      fullPath: '/api/public/bridge/cron-cleanup-drafts'
      preLoaderRoute: typeof ApiPublicBridgeCronCleanupDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/checkout': {
      id: '/api/public/bridge/checkout'
      path: '/api/public/bridge/checkout'
      fullPath: '/api/public/bridge/checkout'
      preLoaderRoute: typeof ApiPublicBridgeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/shopify-oauth/start': {
      id: '/api/public/bridge/shopify-oauth/start'
      path: '/api/public/bridge/shopify-oauth/start'
      fullPath: '/api/public/bridge/shopify-oauth/start'
      preLoaderRoute: typeof ApiPublicBridgeShopifyOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/shopify-oauth/callback': {
      id: '/api/public/bridge/shopify-oauth/callback'
      path: '/api/public/bridge/shopify-oauth/callback'
      fullPath: '/api/public/bridge/shopify-oauth/callback'
      preLoaderRoute: typeof ApiPublicBridgeShopifyOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BridgeAdminRouteChildren {
  BridgeAdminLoginRoute: typeof BridgeAdminLoginRoute
  BridgeAdminProdottiRoute: typeof BridgeAdminProdottiRoute
  BridgeAdminStoresRoute: typeof BridgeAdminStoresRoute
}

const BridgeAdminRouteChildren: BridgeAdminRouteChildren = {
  BridgeAdminLoginRoute: BridgeAdminLoginRoute,
  BridgeAdminProdottiRoute: BridgeAdminProdottiRoute,
  BridgeAdminStoresRoute: BridgeAdminStoresRoute,
}

const BridgeAdminRouteWithChildren = BridgeAdminRoute._addFileChildren(
  BridgeAdminRouteChildren,
)

interface PonteAdminRouteChildren {
  PonteAdminIdRoute: typeof PonteAdminIdRoute
  PonteAdminApplePayRoute: typeof PonteAdminApplePayRoute
  PonteAdminCapiRoute: typeof PonteAdminCapiRoute
  PonteAdminClonesHealthRoute: typeof PonteAdminClonesHealthRoute
  PonteAdminExternalDbRoute: typeof PonteAdminExternalDbRoute
  PonteAdminLoginRoute: typeof PonteAdminLoginRoute
  PonteAdminLogsRoute: typeof PonteAdminLogsRoute
  PonteAdminLovableSyncRoute: typeof PonteAdminLovableSyncRoute
  PonteAdminMigrateSupabaseRoute: typeof PonteAdminMigrateSupabaseRoute
  PonteAdminNewRoute: typeof PonteAdminNewRoute
  PonteAdminProdottiRoute: typeof PonteAdminProdottiRoute
  PonteAdminReferrerCheckRoute: typeof PonteAdminReferrerCheckRoute
  PonteAdminRevenueRoute: typeof PonteAdminRevenueRoute
  PonteAdminShippingRoute: typeof PonteAdminShippingRoute
  PonteAdminSiteSettingRoute: typeof PonteAdminSiteSettingRoute
  PonteAdminSiteSettingsRoute: typeof PonteAdminSiteSettingsRoute
  PonteAdminStoresRoute: typeof PonteAdminStoresRoute
  PonteAdminSyncRoute: typeof PonteAdminSyncRoute
  PonteAdminWashDebugRoute: typeof PonteAdminWashDebugRoute
  PonteAdminIndexRoute: typeof PonteAdminIndexRoute
}

const PonteAdminRouteChildren: PonteAdminRouteChildren = {
  PonteAdminIdRoute: PonteAdminIdRoute,
  PonteAdminApplePayRoute: PonteAdminApplePayRoute,
  PonteAdminCapiRoute: PonteAdminCapiRoute,
  PonteAdminClonesHealthRoute: PonteAdminClonesHealthRoute,
  PonteAdminExternalDbRoute: PonteAdminExternalDbRoute,
  PonteAdminLoginRoute: PonteAdminLoginRoute,
  PonteAdminLogsRoute: PonteAdminLogsRoute,
  PonteAdminLovableSyncRoute: PonteAdminLovableSyncRoute,
  PonteAdminMigrateSupabaseRoute: PonteAdminMigrateSupabaseRoute,
  PonteAdminNewRoute: PonteAdminNewRoute,
  PonteAdminProdottiRoute: PonteAdminProdottiRoute,
  PonteAdminReferrerCheckRoute: PonteAdminReferrerCheckRoute,
  PonteAdminRevenueRoute: PonteAdminRevenueRoute,
  PonteAdminShippingRoute: PonteAdminShippingRoute,
  PonteAdminSiteSettingRoute: PonteAdminSiteSettingRoute,
  PonteAdminSiteSettingsRoute: PonteAdminSiteSettingsRoute,
  PonteAdminStoresRoute: PonteAdminStoresRoute,
  PonteAdminSyncRoute: PonteAdminSyncRoute,
  PonteAdminWashDebugRoute: PonteAdminWashDebugRoute,
  PonteAdminIndexRoute: PonteAdminIndexRoute,
}

const PonteAdminRouteWithChildren = PonteAdminRoute._addFileChildren(
  PonteAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BridgeAdminRoute: BridgeAdminRouteWithChildren,
  CookieRoute: CookieRoute,
  DeployGuideRoute: DeployGuideRoute,
  PonteAdminRoute: PonteAdminRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TerminiRoute: TerminiRoute,
  WashRoute: WashRoute,
  DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute:
    DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiGenerateCheckoutRoute: ApiGenerateCheckoutRoute,
  PSlugRoute: PSlugRoute,
  ShopAccountRoute: ShopAccountRoute,
  ShopCarrelloRoute: ShopCarrelloRoute,
  ShopChiSiamoRoute: ShopChiSiamoRoute,
  ShopContattiRoute: ShopContattiRoute,
  ShopFaqRoute: ShopFaqRoute,
  ShopResiRoute: ShopResiRoute,
  ShopSaleRoute: ShopSaleRoute,
  ShopSpedizioniRoute: ShopSpedizioniRoute,
  ApiBridgeHandshakeRoute: ApiBridgeHandshakeRoute,
  ApiBridgePushShadowProductRoute: ApiBridgePushShadowProductRoute,
  ApiPublicRuntimeSupabaseEnvRoute: ApiPublicRuntimeSupabaseEnvRoute,
  ApiPublicShopifyWebhookRoute: ApiPublicShopifyWebhookRoute,
  ApiPublicSyncProductRoute: ApiPublicSyncProductRoute,
  ApiPublicWhopWebhookRoute: ApiPublicWhopWebhookRoute,
  ShopCategoriaSlugRoute: ShopCategoriaSlugRoute,
  ShopCheckoutDemoRoute: ShopCheckoutDemoRoute,
  ShopCheckoutWhopRoute: ShopCheckoutWhopRoute,
  ShopProdottoSlugRoute: ShopProdottoSlugRoute,
  ApiPublicBridgeCheckoutRoute: ApiPublicBridgeCheckoutRoute,
  ApiPublicBridgeCronCleanupDraftsRoute: ApiPublicBridgeCronCleanupDraftsRoute,
  ApiPublicBridgeCronPollRoute: ApiPublicBridgeCronPollRoute,
  ApiPublicBridgeGenerateCheckoutRoute: ApiPublicBridgeGenerateCheckoutRoute,
  ApiPublicBridgeGetConfigRoute: ApiPublicBridgeGetConfigRoute,
  ApiPublicBridgeHandshakeRoute: ApiPublicBridgeHandshakeRoute,
  ApiPublicBridgePushProductRoute: ApiPublicBridgePushProductRoute,
  ApiPublicBridgeReferrerProbeRoute: ApiPublicBridgeReferrerProbeRoute,
  ApiPublicBridgeShopifyWebhookRoute: ApiPublicBridgeShopifyWebhookRoute,
  ApiPublicBridgeSyncRoute: ApiPublicBridgeSyncRoute,
  ApiPublicBridgeSyncedProductsRoute: ApiPublicBridgeSyncedProductsRoute,
  ApiPublicBridgeUpdateConfigRoute: ApiPublicBridgeUpdateConfigRoute,
  ApiPublicLovableSyncPingRoute: ApiPublicLovableSyncPingRoute,
  ApiPublicLovableSyncPushProductRoute: ApiPublicLovableSyncPushProductRoute,
  ApiPublicBridgeShopifyOauthCallbackRoute:
    ApiPublicBridgeShopifyOauthCallbackRoute,
  ApiPublicBridgeShopifyOauthStartRoute: ApiPublicBridgeShopifyOauthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
